inherit_from: .rubocop_todo.yml

AllCops:
  # Prevent RuboCop from exploding when it finds an older-than-2.2 .ruby-version
  TargetRubyVersion: 2.5
  DisabledByDefault: true
  Exclude: []

Layout/DotPosition:
  Enabled: true
  EnforcedStyle: trailing

Layout/SpaceAroundOperators:
  Enabled: true

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: space

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
