require:
  - rubocop-performance
  - rubocop-rails

inherit_from: .rubocop_todo.yml

AllCops:
  # Prevent RuboCop from exploding when it finds an older-than-2.2 .ruby-version
  TargetRubyVersion: 2.6
  DisabledByDefault: true
  Exclude:
    - "db/schema.rb"

Layout/DotPosition:
  Enabled: true
  EnforcedStyle: trailing

Layout/SpaceAroundOperators:
  Enabled: true

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: space

Style/Documentation:
  Enabled: false

Style/EmptyMethod:
  EnforcedStyle: compact

Style/FrozenStringLiteralComment:
  Enabled: false

Style/HashSyntax:
  EnforcedStyle: hash_rockets
  Exclude:
    - "db/**/*"
    - "config/**/*"

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/SymbolArray:
  EnforcedStyle: brackets

Style/GuardClause:
  Enabled: true

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"
    - "config/**/*"

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    default: "()"

Metrics/LineLength:
  Max: 220

Layout/EmptyLinesAroundClassBody:
  EnforcedStyle: no_empty_lines

Layout/EmptyLinesAroundModuleBody:
  EnforcedStyle: no_empty_lines

Layout/MultilineMethodCallBraceLayout:
  EnforcedStyle: new_line

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
