require:
  - rubocop-performance
  - rubocop-rails

inherit_from: .rubocop_todo.yml

AllCops:
  # Prevent RuboCop from exploding when it finds an older-than-2.2 .ruby-version
  TargetRubyVersion: 2.6
  DisabledByDefault: true
  Exclude:
    - "db/**/*"
    - "config/**/*"
    - "tmp/**/*"
    - "bin/**/*"
    - "Gemfile"
    - "config.ru"

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"

Layout/LineLength:
  Max: 220

# STYLE
Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    default: "()"

Style/Documentation:
  Enabled: false

Style/EmptyMethod:
  EnforcedStyle: compact

Style/FrozenStringLiteralComment:
  EnforcedStyle: always

Style/HashSyntax:
  EnforcedStyle: hash_rockets

Style/StringLiterals:
  EnforcedStyle: double_quotes
  ConsistentQuotesInMultiline: true

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/SymbolArray:
  EnforcedStyle: brackets

Style/GuardClause:
  Enabled: true

Style/Alias:
  EnforcedStyle: prefer_alias_method

Style/AndOr:
  EnforcedStyle: conditionals

Style/AsciiComments:
  Enabled: false

Style/BarePercentLiterals:
  Enabled: false

Style/ClassAndModuleChildren:
  EnforcedStyle: nested
  AutoCorrect: true

Style/ClassCheck:
  EnforcedStyle: is_a?

Style/CommentAnnotation:
  Keywords:
    - NB
    - TODO
    - FIXME
    - OPTIMIZE
    - HACK
    - REVIEW

Style/DefWithParentheses:
  Enabled: true

Style/GlobalVars:
  AllowedVariables:
    - "$redis"

Style/MethodCallWithArgsParentheses:
  Enabled: true
  IgnoreMacros: true
  IgnoredMethods:
    - "describe"
    - "to"
    - "to_not"
    - "require"
    - "change"
    - "puts"
    - "exit"

Style/MethodDefParentheses:
  EnforcedStyle: require_parentheses

Style/RedundantParentheses:
  Enabled: false

# LAYOUT
Layout/DotPosition:
  EnforcedStyle: trailing

Layout/SpaceAroundOperators:
  Enabled: true

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: space
  EnforcedStyleForEmptyBraces: no_space

Layout/CaseIndentation:
  EnforcedStyle: end

Layout/EmptyLineBetweenDefs:
  AllowAdjacentOneLineDefs: true

Layout/EndAlignment:
  EnforcedStyleAlignWith: start_of_line
  AutoCorrect: true

Layout/FirstMethodArgumentLineBreak:
  Enabled: true

Layout/MultilineArrayBraceLayout:
  EnforcedStyle: new_line

Layout/MultilineHashBraceLayout:
  EnforcedStyle: new_line

Layout/EmptyLinesAroundClassBody:
  EnforcedStyle: no_empty_lines

Layout/EmptyLinesAroundModuleBody:
  EnforcedStyle: no_empty_lines

Layout/MultilineMethodCallBraceLayout:
  EnforcedStyle: new_line

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

# LINT
Lint/AmbiguousBlockAssociation:
  Exclude:
    - "spec/**/*" # Ignoring the whole spec directory because `change` is the only method that triggers this
