development: &default
  adapter: postgresql
  encoding: utf8
  database: <%= ENV["DATABASE_NAME"] %>
  pool: 5
  username: <%= ENV["DATABASE_USER"] %>
  password: <%= ENV["DATABASE_PASS"] %>
  port: <%= ENV.fetch("DATABASE_PORT") { 5432 } %>

test:
  <<: *default
  database: <%= ENV["DATABASE_TEST_NAME"] %>
  host: 127.0.0.1

production:
  <<: *default
