development: &default
  adapter: postgresql
  encoding: utf8
  database: <%= Rails.application.credentials.database[:name] %>
  pool: 5
  username: <%= Rails.application.credentials.database[:username] %>
  password: <%= Rails.application.credentials.database[:password] %>
  port: <%= ENV.fetch("DATABASE_PORT") { 5432 } %>

test:
  <<: *default
  database: <%= Rails.application.credentials.database[:test_name] %>
  host: 127.0.0.1

production:
  <<: *default
