development: &default
  adapter: postgresql
  encoding: unicode
  database: gastracker2_development
  pool: 5
  username: postgres
  password: postgres

test:
  <<: *default
  database: gastracker2_test
